import { useState } from 'react';
import type { Background, GeneratedImage, ModelChoice } from '../types';
import { demoGenerate } from '../lib/image';
import { generateAiImages } from '../lib/api';

export function ImageGenerator({original,category,productName,model,setModel,background,setBackground,customBackground,setCustomBackground,generated,setGenerated,onError}:{original:string;category:string;productName:string;model:ModelChoice;setModel:(v:ModelChoice)=>void;background:Background;setBackground:(v:Background)=>void;customBackground:string;setCustomBackground:(v:string)=>void;generated:GeneratedImage[];setGenerated:(v:GeneratedImage[])=>void;onError:(v:string)=>void}){
 const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [aiConfigured,setAiConfigured]=useState<boolean|null>(null);
 async function generate(){ if(!original){onError('Upload a product image first.');return;} setBusy(true);setProgress(10); try{
   const steps=[25,45,65,82,100]; for(const p of steps){await new Promise(r=>setTimeout(r,220));setProgress(p)}
   let result;
   try { result=await generateAiImages({imageDataUrl:original,background,customBackground,model,category,productName}); setAiConfigured(true); }
   catch(err){ setAiConfigured(false); result=await demoGenerate(original,background,customBackground,model); if(err instanceof Error && !err.message.includes('not configured')) onError(`${err.message} Switched to Demo Mode.`); }
   setGenerated(result.map((x,i)=>({id:`${Date.now()}-${i}`,title:x.title,url:x.url,mode:aiConfigured===true?'ai':'demo'})));
 }catch(e){onError(e instanceof Error?e.message:'Image generation failed.')}finally{setBusy(false);setProgress(0)} }
 async function regenerate(id:string){const old=generated.find(x=>x.id===id);if(!old)return; try{const result=await demoGenerate(original,background,customBackground,model);const next=result.find(x=>x.title===old.title)||result[0];setGenerated(generated.map(x=>x.id===id?{...x,url:next.url,mode:'demo'}:x));onError('Individual regeneration is running in Demo Mode unless an AI provider is configured.');}catch(e){onError(e instanceof Error?e.message:'Could not regenerate image.')} }
 function download(url:string,title:string){const a=document.createElement('a');a.href=url;a.download=`${title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.jpg`;document.body.appendChild(a);a.click();a.remove();}
 async function downloadAll(){for(const x of generated){download(x.url,x.title);await new Promise(r=>setTimeout(r,180));}}
 return <div className="card p-4 sm:p-6">
   <div className="grid gap-4 md:grid-cols-3"><Field label="Model / wearer"><select className="input" value={model} onChange={e=>setModel(e.target.value as ModelChoice)}><option value="none">No model</option><option value="male">Male model</option><option value="female">Female model</option></select></Field><Field label="Background"><select className="input" value={background} onChange={e=>setBackground(e.target.value as Background)}><option value="white">White</option><option value="grey">Light grey</option><option value="lifestyle">Lifestyle</option><option value="custom">Custom</option></select></Field>{background==='custom'?<Field label="Custom background"><input className="input" value={customBackground} onChange={e=>setCustomBackground(e.target.value)} placeholder="Describe the background" maxLength={120}/></Field>:<div className="hidden md:block"/>}</div>
   <div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm text-blue-900"><b>Demo Mode is always available.</b> If no authorized AI image API is configured, the app creates 5 catalog layouts from your original image and clearly labels them as Demo Mode.</div>
   <button className="btn btn-primary mt-4 w-full sm:w-auto" onClick={()=>void generate()} disabled={busy}>{busy?`Generating ${progress}%…`:'Generate Images'}</button>
   {busy&&<div className="mt-3 h-2 overflow-hidden rounded-full bg-gray-200"><div className="h-full bg-gray-900 transition-all" style={{width:`${progress}%`}}/></div>}
   {generated.length>0&&<><div className="mt-6 flex items-center justify-between gap-3"><div><h3 className="font-bold">Catalog images</h3><p className="text-xs text-gray-500">{generated.length} image{generated.length===1?'':'s'} • {generated[0].mode==='ai'?'AI generated':'Demo Mode templates'}</p></div><button className="btn btn-secondary text-sm" onClick={()=>void downloadAll()}>Download all</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{generated.map(x=><article key={x.id} className="overflow-hidden rounded-2xl border border-gray-200"><img src={x.url} alt={x.title} className="aspect-[4/5] w-full object-cover bg-gray-100"/><div className="p-3"><div className="flex items-start justify-between gap-2"><div><h4 className="font-bold text-sm">{x.title}</h4><span className={`badge mt-1 ${x.mode==='ai'?'bg-violet-100 text-violet-700':'bg-gray-100 text-gray-600'}`}>{x.mode==='ai'?'AI':'DEMO'}</span></div></div><div className="mt-3 flex gap-2"><button className="btn btn-secondary flex-1 text-xs" onClick={()=>download(x.url,x.title)}>Download</button><button className="btn btn-secondary flex-1 text-xs" onClick={()=>void regenerate(x.id)}>Regenerate</button></div></div></article>)}</div></>}
   {aiConfigured===false&&<p className="mt-4 text-sm font-semibold text-amber-700">AI generation is not configured or unavailable. Nothing was falsely marked as AI; these are Demo Mode layouts.</p>}
 </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}
