import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import type { Background, ModelChoice, PriceInputs, ProductInfo, ProjectState, GeneratedImage } from './types';
import { loadProject, saveProject, clearProject } from './lib/storage';
import { chargeableWeight, calculatePrice } from './lib/calculations';
import { UploadCard } from './components/UploadCard';
import { ProductDetails } from './components/ProductDetails';
import { ImageGenerator } from './components/ImageGenerator';
import { ShippingHelper } from './components/ShippingHelper';
import { PriceCalculator } from './components/PriceCalculator';
import { Dashboard } from './components/Dashboard';
import { Section } from './components/Section';
import { Toast } from './components/Toast';

const defaultProduct:ProductInfo={name:'',category:'',hsn:'',productCost:0,sellingPrice:0,weight:0,length:0,width:0,height:0};
const defaultPrice:PriceInputs={productCost:0,packagingCost:0,otherCosts:0,marketplacePct:0,shippingCost:0,desiredProfit:0,gstPct:0};
function App(){
 const existing=loadProject();
 const [product,setProduct]=useState<ProductInfo>(existing?.product||defaultProduct); const [price,setPrice]=useState<PriceInputs>(existing?.price||defaultPrice); const [image,setImage]=useState(existing?.originalImageDataUrl||''); const [generated,setGenerated]=useState<GeneratedImage[]>(existing?.generated||[]); const [model,setModel]=useState<ModelChoice>(existing?.model||'none'); const [background,setBackground]=useState<Background>(existing?.background||'white'); const [customBackground,setCustomBackground]=useState(existing?.customBackground||''); const [toast,setToast]=useState<string|null>(null); const [mobileOpen,setMobileOpen]=useState(false);
 useEffect(()=>{try{saveProject({product,price,originalImageDataUrl:image,generated,model,background,customBackground,updatedAt:Date.now()});}catch(e){setToast(e instanceof Error?e.message:'Could not save project.');}},[product,price,image,generated,model,background,customBackground]);
 const charge=useMemo(()=>chargeableWeight(product.weight,product.length,product.width,product.height),[product]); const priceResult=useMemo(()=>calculatePrice(price),[price]);
 function updateImage(v:string){setImage(v);if(!v)setGenerated([]);} function clear(){if(!window.confirm('Clear this project and remove its locally saved data?'))return;clearProject();setProduct(defaultProduct);setPrice(defaultPrice);setImage('');setGenerated([]);setToast('Project cleared.');}
 function nav(id:string){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMobileOpen(false)}
 const navItems=[['dashboard','Dashboard'],['upload','Upload Product'],['images','Generate Images'],['shipping','Shipping Helper'],['price','Price Calculator'],['details','Product Details'],['catalog','Download Catalog']];
 return <div className="min-h-screen bg-[#f5f7fb]">
  <header className="sticky top-0 z-40 border-b border-gray-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gray-900 font-black text-white">S</div><div><div className="font-extrabold leading-tight">Seller Image & Price Helper</div><div className="text-xs text-gray-500">Catalog tools for marketplace sellers</div></div></div><div className="flex items-center gap-2"><span className="badge bg-amber-100 text-amber-800">DEMO MODE READY</span><button className="btn btn-secondary hidden sm:inline-flex" onClick={clear}>Clear Project</button><button className="btn btn-secondary sm:hidden" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">☰</button></div></div>{mobileOpen&&<nav className="border-t border-gray-200 bg-white p-3 sm:hidden">{navItems.map(([id,label])=><button key={id} onClick={()=>nav(id)} className="block w-full rounded-lg px-3 py-2 text-left text-sm font-semibold hover:bg-gray-50">{label}</button>)}<button onClick={clear} className="mt-2 w-full rounded-lg bg-rose-50 px-3 py-2 text-left text-sm font-semibold text-rose-700">Clear Project</button></nav>}</header>
  <div className="mx-auto flex max-w-7xl gap-6 px-4 py-6 sm:px-6"><aside className="sticky top-24 hidden h-fit w-56 shrink-0 lg:block"><nav className="card p-3">{navItems.map(([id,label],i)=><button key={id} onClick={()=>nav(id)} className={`mb-1 w-full rounded-lg px-3 py-2 text-left text-sm font-semibold ${i===0?'bg-gray-900 text-white':'text-gray-600 hover:bg-gray-50'}`}>{label}</button>)}</nav></aside><main className="min-w-0 flex-1 space-y-8">
   <section id="dashboard" className="scroll-mt-24"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><span className="badge bg-blue-100 text-blue-700">SELLER TOOLKIT</span><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Make better catalogs. Plan prices faster.</h1><p className="mt-2 max-w-2xl text-sm text-gray-600">Upload one product image, build catalog-ready layouts in Demo Mode, estimate chargeable weight, and calculate a practical selling-price range.</p></div></div><Dashboard product={product} suggestedProfit={priceResult.requiredPrice} chargeable={charge} generatedCount={generated.length} onNavigate={nav}/></section>
   <Section id="upload" title="1. Upload Product" subtitle="Your project stays in this browser unless you explicitly configure an AI service."><UploadCard image={image} onImage={updateImage} onError={setToast}/></Section>
   <Section id="images" title="2. Generate Catalog Images" subtitle="Five variations are created in Demo Mode immediately. AI mode requires a secure server-side API configuration."><ImageGenerator original={image} category={product.category} productName={product.name} model={model} setModel={setModel} background={background} setBackground={setBackground} customBackground={customBackground} setCustomBackground={setCustomBackground} generated={generated} setGenerated={setGenerated} onError={setToast}/></Section>
   <Section id="shipping" title="3. Shipping Cost Helper" subtitle="Uses actual vs volumetric weight. All marketplace shipping outputs are estimates."><ShippingHelper product={product} onChange={setProduct}/></Section>
   <Section id="price" title="4. Selling Price Calculator" subtitle="Use your costs and desired profit to create sensible price options."><PriceCalculator value={price} onChange={v=>{setPrice(v);setProduct(p=>({...p,productCost:v.productCost,sellingPrice:p.sellingPrice}))}} onApply={v=>{setProduct(p=>({...p,sellingPrice:v}));setToast(`Selling price set to ₹${v.toFixed(0)}.`)}}/></Section>
   <Section id="details" title="5. Product Information" subtitle="Required fields are validated before you rely on the dashboard. HSN is never invented automatically."><ProductDetails value={product} onChange={p=>{setProduct(p);setPrice(x=>({...x,productCost:p.productCost}))}}/></Section>
   <Section id="catalog" title="6. Download Catalog" subtitle="Download your generated images individually or from the Generate Images section."><div className="card p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">Catalog package</h3><p className="text-sm text-gray-500">{generated.length ? `${generated.length} generated image${generated.length===1?'':'s'} ready.` : 'Generate images first.'}</p></div>{generated.length>0?<button className="btn btn-primary" onClick={()=>{for(const x of generated){const a=document.createElement('a');a.href=x.url;a.download=`${x.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.jpg`;a.click();}}}>Download all images</button>:<button className="btn btn-secondary" onClick={()=>nav('images')}>Go to image generator</button>}</div></div></Section>
   <footer className="pb-8 text-xs leading-5 text-gray-500">Price and shipping calculations are estimates. Actual marketplace fees, shipping charges, taxes and customer discounts may vary. This app does not guarantee Meesho shipping charges, scrape Meesho, or bypass marketplace rules. AI services are optional and require your own authorized provider configuration.</footer>
  </main></div><Toast message={toast} onClose={()=>setToast(null)}/></div>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
